version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1.14-fpm-node-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t test .
      - run: docker tag test ncar/test:$CIRCLE_BUILD_NUM
      - run: docker images --all
