version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:9-jdk-node-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install aws
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run: docker build -t test .
      - run: docker tag test ncar/test:$CIRCLE_BUILD_NUM
      - run: docker images --all
